name: Publish X10 toolkit

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
  CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
  GPG_PRIVATE_KEY: ${{ secrets.PGP_SECRET }}
  PGP_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}

jobs:
  publish:
    name: Release toolkit and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v6.3

      - name: Setup Scala CLI
        uses: VirtusLab/scala-cli-setup@main

      - name: Import GPG key
        id: import_gpg
        run: |
          echo "${{ secrets.PGP_SECRET }}" | base64 --decode > private.key
          gpg --import --batch --yes --pinentry-mode loopback --passphrase "${{ secrets.PGP_PASSPHRASE }}" private.key
          echo "fingerprint=$(gpg --list-secret-keys --with-colons | grep -m 1 fpr | awk -F: '/^fpr:/ { print $10 }')" >> "$GITHUB_OUTPUT"
          rm private.key
        env:
          gpg_private_key: ${{ secrets.PGP_SECRET }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}

      - name: Publish Toolkit for JVM
        run: |
          scala-cli --power publish local X10Toolkit.scala publish-conf.scala --gpg-key $PGP_KEY_ID --gpg-option --pinentry-mode --gpg-option loopback --gpg-option --passphrase --gpg-option $PGP_PASSWORD
          tar -czvf central-bundle.tgz \
            -C ~/.ivy2/local/dev.alteration.x10/toolkit_3/$TOOLKIT_VERSION/docs . \
            -C ~/.ivy2/local/dev.alteration.x10/toolkit_3/$TOOLKIT_VERSION/poms . \
            -C ~/.ivy2/local/dev.alteration.x10/toolkit_3/$TOOLKIT_VERSION/jars . \
            -C ~/.ivy2/local/dev.alteration.x10/toolkit_3/$TOOLKIT_VERSION/srcs .
          curl --request POST \
            --verbose \
            --header 'Authorization: Bearer ZXhhbXBsZV91c2VybmFtZTpleGFtcGxlX3Bhca3N3b3JkCg==' \
            --form bundle=@central-bundle.tgz \
            https://central.sonatype.com/api/v1/publisher/upload
            rm central-bundle.tgz
        continue-on-error: false
        env:
          PGP_KEY_ID: ${{ steps.import_gpg.outputs.fingerprint }}
          TOOLKIT_VERSION: ${{ github.ref_name }}

      - name: Publish Toolkit Test for JVM
        run: |
          scala-cli --power publish local --dependency "dev.alteration.x10::toolkit::$TOOLKIT_VERSION" X10ToolkitTest.scala publish-conf.scala --gpg-key $PGP_KEY_ID --gpg-option --pinentry-mode --gpg-option loopback --gpg-option --passphrase --gpg-option $PGP_PASSWORD
          tar -czvf central-bundle.tgz \
            -C ~/.ivy2/local/dev.alteration.x10/toolkit_3/$TOOLKIT_VERSION/docs . \
            -C ~/.ivy2/local/dev.alteration.x10/toolkit_3/$TOOLKIT_VERSION/poms . \
            -C ~/.ivy2/local/dev.alteration.x10/toolkit_3/$TOOLKIT_VERSION/jars . \
            -C ~/.ivy2/local/dev.alteration.x10/toolkit_3/$TOOLKIT_VERSION/srcs .
          curl --request POST \
            --verbose \
            --header 'Authorization: Bearer $CENTRAL_TOKEN' \
            --form bundle=@central-bundle.tgz \
            https://central.sonatype.com/api/v1/publisher/upload
          rm central-bundle.tgz
        continue-on-error: true
        env:
          TOOLKIT_VERSION: ${{ github.ref_name }}
          PGP_KEY_ID: ${{ steps.import_gpg.outputs.fingerprint }}
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
    