name: Publish X10 toolkit

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
  CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
  GPG_PRIVATE_KEY: ${{ secrets.PGP_SECRET }}
  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}

jobs:
  publish:
    name: Release toolkit and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v6.3

      - name: Setup Scala CLI
        uses: VirtusLab/scala-cli-setup@main

      - name: Import GPG key
        id: import_gpg
        run: |
          echo "${{ secrets.PGP_SECRET }}" | base64 --decode > private.key
          gpg --import --batch --yes --pinentry-mode loopback --passphrase "${{ secrets.PGP_PASSPHRASE }}" private.key
          echo "fingerprint=$(gpg --list-secret-keys --with-colons | grep -m 1 fpr | awk -F: '/^fpr:/ { print $10 }')" >> "$GITHUB_OUTPUT"
          rm private.key
        env:
          gpg_private_key: ${{ secrets.PGP_SECRET }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}

      - name: Publish Toolkit for JVM
        run: |
          sudo apt-get update
          sudo apt-get install rename
          make -s x10-bundle
          make -s x10-publish
          make -s clean
        continue-on-error: false
        env:
          PGP_KEY_ID: ${{ steps.import_gpg.outputs.fingerprint }}
          TOOLKIT_VERSION: ${{ github.ref_name }}
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
